services:
  - type: web
    name: gorden-yulie-batu-api
    runtime: php
    region: singapore
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://gorden-yulie-batu-api.onrender.com
      - key: PHP_VERSION
        value: 8.2.0
      - key: DATABASE_URL
        fromDatabase:
          name: gorden-yulie-batu-db
          property: connectionString

databases:
  - name: gorden-yulie-batu-db
    databaseName: gorden_yulie_batu
    user: gordenyulie
    plan: free
